"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"				"9999999"
		"ypos"				"9999999"
		"zpos"				"0"
		"wide"				"0"
		"tall"				"0"
		"visible"			"1"
		"enabled"			"1"
		"scaleImage"		"1"
		"image"				"../hud/color_panel_brown"
		"scaleImage"		"1"
		"teambg_1"			"../hud/color_panel_brown"
		"teambg_2"			"../hud/color_panel_red"
		"teambg_3"			"../hud/color_panel_blu"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"4"
		"draw_corner_height" 	"4"
	}
	
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"0"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/color_panel_brown"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/color_panel_red"
		"teambg_3"		"../hud/color_panel_blu"
		"Alpha"			"255"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"4"
		"draw_corner_height" 	"4"		
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"G_FontAmmo"
		"fgcolor"		"G_AmmoClipValue"
		"xpos"			"c100"
		"ypos"			"r78"
		"zpos"			"5"
		"wide"			"124"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%Ammo%"
		"paintbackgroundtype"	"2"
		"textinsetx"	"5"
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"pin_to_sibling" "AmmoInClip"
		"font"			"G_FontAmmo"
		"fgcolor"		"G_XPBar"
		"xpos"			 "-1"
		"ypos"			 "-2"
		"zpos"			"5"
		"wide"			"124"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%Ammo%"
		"paintbackgroundtype"	"2"
		"textinsetx"	"5"
	}
	
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"G_FontMedium"
		"fgcolor"		"G_AmmoReserveValue"
		"xpos"			"c170"
		"ypos"			"r56"
		"zpos"			"7"
		"wide"			"50"
		"tall"			"25"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%AmmoInReserve%"
		"textinsetx"	"5"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"G_FontMedium"
		"fgcolor"		"G_XPBar"
		"xpos"			"-1"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"50"
		"tall"			"25"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%AmmoInReserve%"
		"textinsetx"	"5"
		"pin_to_sibling" "AmmoInReserve"
	}									
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"G_FontAmmo"
		"fgcolor"		"G_AmmoClipValue"
		"xpos"			"c100"
		"ypos"			"r78"
//		"ypos"			"r60"
		"zpos"			"5"
		"wide"			"124"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%Ammo%"
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"G_FontAmmo"
		"fgcolor"		"G_XPBar"
		"xpos"			"-1"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"124"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%Ammo%"
		"pin_to_sibling" "AmmoNoClip"
	}								
	"AmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"AmmoBG"
		"pin_to_sibling" "AmmoInClip"
		"xpos"			"6"
		"ypos"			"0"
		"zpos"			"-5"
		"wide"			"131"
		"tall"			"54"
		"visible"		"1"
		"enabled"		"1"
		"image"				"../hud/color_panel_brown"
		"scaleImage"		"1"
		"teambg_1"			"../hud/color_panel_brown"
		"teambg_2"			"../hud/color_panel_red"
		"teambg_3"			"../hud/color_panel_blu"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"4"
		"draw_corner_height" 	"4"
		"alpha" "0"
	}	
	"AmmoLowBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"AmmoLowBG"
		"pin_to_sibling" "AmmoNoClip"
		"xpos"			"4"
		"ypos"			"-2"
		"zpos"			"-4"
		"wide"			"128"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"image"				"../hud/color_panel_brown"
		"scaleImage"		"1"
		"teambg_1"			"../hud/color_panel_brown"
		"teambg_2"			"../hud/color_panel_red"
		"teambg_3"			"../hud/color_panel_blu"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"4"
		"draw_corner_height" 	"4"
	}
}
