"Resource/UI/HudMedicCharge.res"
{	
	"Background"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"Background"
		"xpos"			"121212121"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"130"
		"tall"			"65"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/medic_charge_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/medic_charge_red_bg"
		"teambg_3"		"../hud/medic_charge_blue_bg"				
	}
	"anchorBOX"
	{	
		"ControlName"	"EditablePanel"
		"fieldName"		"anchorBOX"
		"xpos"					"cs-0.5"
		"ypos"					"c132"
		"zpos"			"2"
		"wide"			"128"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"	"0 0 0 255"
	}
	"BadBoxMeter"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"BadBoxMeter"
		"xpos"		    "4"
		"ypos"		    "4"
		"zpos"		    "-100"
		"wide"		    "135"
		"tall"		    "15"
		"autoResize"	"0"
		"pinCorner"	    "0"
		"visible"		"1"
		"enabled"		"1"
		"pin_to_sibling"	"anchorBOX"
		"image"			"../hud/color_panel_brown"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/color_panel_red"
		"teambg_3"		"../hud/color_panel_blu"
		"Alpha"			"255"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"4"
		"draw_corner_height" 	"4"		
		"alpha"			"0"
	}
	"BadBox"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"BadBox"
		"xpos"		    "6"
		"ypos"		    "0"
		"zpos"		    "-6"
		"wide"		    "131"
		"tall"		    "54"
		"autoResize"	"0"
		"pinCorner"	    "0"
		"visible"		"1"
		"enabled"		"1"
		"pin_to_sibling"	"ChargeLabel"
		"image"			"../hud/color_panel_brown"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/color_panel_red"
		"teambg_3"		"../hud/color_panel_blu"
		"Alpha"			"255"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"4"
		"draw_corner_height" 	"4"		
		"alpha"			"0"
	}
	"BadBoxInner"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"BadBoxInner"
		"xpos"		    "4"
		"ypos"		    "-2"
		"zpos"		    "-5"
		"wide"		    "128"
		"tall"		    "50"
		"autoResize"	"0"
		"pinCorner"	    "0"
		"visible"		"1"
		"enabled"		"1"
		"pin_to_sibling"	"ChargeLabel"
		"alpha"			"255"
		"image"			"../hud/color_panel_brown"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/color_panel_red"
		"teambg_3"		"../hud/color_panel_blu"
		"Alpha"			"255"
		"src_corner_height"		"16"
		"src_corner_width"		"16"
		"draw_corner_width"		"4"
		"draw_corner_height" 	"4"		
	}
	"Modulate"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"Modulate"
		"xpos"					""
		"ypos"					""
		"zpos"		    "3"
		"wide"		    "128"
		"tall"		    "8"
		"visible"		"1"
		"enabled"		"1"
		"BgColor_Override"		"244 114 43 50"
		"scaleImage"	"1"
		"image"			"../vgui/replay/thumbnails/modulatetest"
		"drawcolor"		"AchiOrange"
		"paintBorder"	"1"
		"border"		"NoBorder"
		"pin_to_sibling" "anchorBOX"
	}
	"ChargeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabel"
		"xpos"			"c100"
		"ypos"			"r78"
		"zpos"			"5"
		"wide"			"124"
		"tall"			"50"
		"tall_minmode"	"50"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"	"#TF_UberchargeMinHUD"
		"font"			"G_FontHealth"
		"fgcolor"		"G_HealthValue"
	}
	"IndividualChargesLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"IndividualChargesLabel"
		"xpos"			"c100"
		"ypos"			"r78"
		"zpos"			"5"
		"wide"			"124"
		"tall"			"50"
		"tall_minmode"	"50"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"	"#TF_IndividualUberchargesMinHUD"
		"font"			"G_FontHealth"
		"fgcolor"		"G_HealthValue"
	}
	
	"ChargeMeter"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"					"cs-0.5"
		"ypos"					"c132"
		"zpos"			"2"
		"wide"			"128"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"Black"
	}		

	"ChargeMeter1"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter1"
		"font"			"Default"
		"xpos"			"54"
		"ypos"			"5"
		"zpos"			"2"
		"wide"			"30"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"Black"
		"pin_to_sibling" "ResistIcon"
	}

	"ChargeMeter2"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter2"
		"font"			"Default"
		"xpos"			"-32"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"30"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"Black"
		"pin_to_sibling" "ChargeMeter1"
	}

	"ChargeMeter3"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter3"
		"font"			"Default"
		"xpos"			"-32"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"30"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"Black"
		"pin_to_sibling" "ChargeMeter2"
	}

	"ChargeMeter4"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter4"
		"font"			"Default"
		"xpos"			"-32"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"32"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"Black"
		"pin_to_sibling" "ChargeMeter3"
	}
	
	"HealthClusterIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HealthClusterIcon"
		"xpos"			"cs-0.5"
		"ypos"			"c137"
		"wide"			"20"
		"tall"			"o1"
		"visible"		"1"
		"visible_minmode"		"0"
		"enabled"		"1"
		"image"			""
		"scaleImage"	"1"	
	}	
	
	"ResistIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ResistIcon"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"20"
		"tall"			"20"
		"visible"		"1"
		"visible_minmode"		"1"
		"enabled"		"1"
		"image"			"../HUD/defense_buff_bullet_blue"
		"scaleImage"	"1"	
		"pin_to_sibling" "HealthClusterIcon"
	}
	
}
